name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - uses: pnpm/action-setup@v4.1.0
      with:
        version: 8
        run_install: true
    - name: Lint
      run: |
        pnpm lint
    - name: Test
      run: |
        pnpm test
    - name: Build
      run: |
        pnpm build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
